### ISSUE TITLE
Error {"message":"auth error} when pressing on the logo from the 'add a new saving goal' or diary entry/quiz etc page 

### ISSUE THREAD

**Issue by SylwiaMe** [pat-shannon/mean-money#108]
### Feature

Nav bar

### Suggested Priority

High

### Observed Behaviour

The pop up with the error shows up when clicking on the logo (shark) from diary/goals/quiz page. 
<img width="197" alt="Screenshot 2024-12-18 at 16 09 14" src="https://github.com/user-attachments/assets/644a5724-5750-45b2-9208-5461e637fb57" />

### Expected Behaviour

- page should take us to dashboard with no errors 
- if there should be some message please replace {"message":"auth error}  with the message for the user 

### Reproduction Steps

1. Log in
2. click e.g on 'add a diary entry' 
3. when on 'add diary entry' page - click logo (shark) to go back to the dashboard 
4. error should pop up on the top right

**Comment by pat-shannon** [comment]
can't seem to reproduce this, had your token expired?
